def retrun_countries():
    COUNTRIES_MAPPING = {
        "Egypt": "EG",
        "United States": "US",
        "China": "CN",
        "Germany": "DE",
        "France": "FR",
        "United Kingdom": "GB",
        "India": "IN",
        "Japan": "JP",
        "Brazil": "BR",
        "Canada": "CA",
        "Italy": "IT",
        "Spain": "ES",
        "Saudi Arabia": "SA",
        "Russian Federation": "RU",
        "Turkey": "TR",
        "South Africa": "ZA",
        "Australia": "AU",
        "Argentina": "AR",
        "Mexico": "MX",
        "Indonesia": "ID",
        "Netherlands": "NL",
        "Switzerland": "CH",
        "Sweden": "SE",
        "Norway": "NO",
        "Denmark": "DK",
        "Finland": "FI",
        "Poland": "PL",
        "Belgium": "BE",
        "Austria": "AT",
        "Ireland": "IE",
        "Israel": "IL",
        "Singapore": "SG",
        "Malaysia": "MY",
        "Thailand": "TH",
        "Philippines": "PH",
        "Vietnam": "VN",
        "Pakistan": "PK",
        "Bangladesh": "BD",
        "Nigeria": "NG",
        "Kenya": "KE",
        "Ethiopia": "ET",
        "Morocco": "MA",
        "Algeria": "DZ",
        "Tunisia": "TN",
        "Ghana": "GH",
        "Angola": "AO",
        "Ukraine": "UA",
        "Czech Republic": "CZ",
        "Hungary": "HU",
        "Romania": "RO",
        "Bulgaria": "BG",
        "Greece": "GR",
        "Portugal": "PT",
        "Slovakia": "SK",
        "Slovenia": "SI",
        "Croatia": "HR",
        "Serbia": "RS",
        "Belarus": "BY",
        "Kazakhstan": "KZ",
        "Uzbekistan": "UZ",
        "Qatar": "QA",
        "United Arab Emirates": "AE",
        "Kuwait": "KW",
        "Oman": "OM",
        "Jordan": "JO",
        "Lebanon": "LB",
        "Iraq": "IQ",
        "Iran": "IR",
        "Afghanistan": "AF",
        "Sri Lanka": "LK",
        "Nepal": "NP",
        "Myanmar": "MM",
        "Cambodia": "KH",
        "Laos": "LA",
        "New Zealand": "NZ",
        "Chile": "CL",
        "Colombia": "CO",
        "Peru": "PE",
        "Venezuela": "VE",
        "Ecuador": "EC",
        "Bolivia": "BO",
        "Paraguay": "PY",
        "Uruguay": "UY",
        "Costa Rica": "CR",
        "Panama": "PA",
        "Dominican Republic": "DO",
        "Guatemala": "GT",
        "Honduras": "HN",
        "El Salvador": "SV",
        "Iceland": "IS",
        "Luxembourg": "LU",
        "Estonia": "EE",
        "Latvia": "LV",
        "Lithuania": "LT",
        "Cyprus": "CY",
        "Malta": "MT"
    }
    return COUNTRIES_MAPPING